package Tp_1920_JoaoValente_2017016033.logica;

public enum InteracaoEsperada {
    CONVERT_RESOURCES, EVENT, GAME_OVER, LAND_ON_THE_PLANET, LAST_CHANCE, SPACE_STATION, SPACE_TRAVEL,
    WAITING_SHIP_SELECTION
}
